# - name: Ensure /var/secrets directory exists
#   file:
#     path: /var/secrets
#     state: directory
#     owner: hng
#     group: hng
#     mode: '0700'
    
postgres_admin_password: "password"
postgres_user_password: "password"
