---
# Ensure this file contains only tasks, no play definitions
- name: Clone the repository
  git:
    repo: 'https://github.com/hngprojects/hng_boilerplate_php_laravel_web.git'
    version: devops
    dest: /opt/stage_5b
    update: yes
    force: yes

- name: Ensure the app directory is owned by hng
  file:
    path: /opt/stage_5b
    owner: hng
    group: hng
    recurse: yes

- name: Copy .env file
  copy:
    src: /opt/stage_5b/.env.example
    dest: /opt/stage_5b/.env
    remote_src: yes

- name: Update .env file for DB connection
  lineinfile:
    path: /opt/stage_5b/.env
    regexp: '^DB_CONNECTION='
    line: 'DB_CONNECTION=pgsql'

- name: Update .env file for DB host
  lineinfile:
    path: /opt/stage_5b/.env
    regexp: '^DB_HOST='
    line: 'DB_HOST=127.0.0.1'

- name: Update .env file for DB port
  lineinfile:
    path: /opt/stage_5b/.env
    regexp: '^DB_PORT='
    line: 'DB_PORT=5432'

- name: Update .env file for DB database
  lineinfile:
    path: /opt/stage_5b/.env
    regexp: '^DB_DATABASE='
    line: 'DB_DATABASE=stage_5b'

- name: Update .env file for DB password
  lineinfile:
    path: /opt/stage_5b/.env
    regexp: '^DB_PASSWORD='
    line: 'DB_PASSWORD={{ postgres_user_password }}'

- name: Download Composer installer
  command: curl -v https://getcomposer.org/installer | php
  args:
    chdir: /tmp
  register: composer_install_output
  ignore_errors: yes  # To proceed with other tasks even if this fails

- name: Debug Composer install output
  debug:
    msg: "{{ composer_install_output.stdout }}"
  when: composer_install_output is defined

- name: Debug Composer install error
  debug:
    msg: "{{ composer_install_output.stderr }}"
  when: composer_install_output is defined and composer_install_output.stderr | length > 0
