---
- name: Install required packages
  apt:
    name:
      - git
      - software-properties-common
      - nginx
      - redis-server
      - php8.2
      - php8.2-cli
      - php8.2-pgsql
      - php8.2-mbstring
      - php8.2-xml
      - php8.2-curl
      - php8.2-zip
      - unzip
    state: present
    update_cache: yes

- name: Add PHP repository
  apt_repository:
    repo: ppa:ondrej/php
    state: present
    update_cache: yes

- name: Install Composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-setup.php

- name: Install Composer globally
  command: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer

- name: Remove Composer installer
  file:
    path: /tmp/composer-setup.php
    state: absent
