---
- name: Install required packages
  apt:
    name:
      - git
      - postgresql
      - postgresql-contrib
      - nginx
      - redis-server
      - php8.2
      - php8.2-cli
      - php8.2-pgsql
      - php8.2-mbstring
      - php8.2-xml
      - php8.2-curl
      - php8.2-zip
      - composer
    state: present
    update_cache: yes
