---
- name: Ensure PostgreSQL service is running
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Update PostgreSQL authentication method to md5
  lineinfile:
    path: /etc/postgresql/16/main/pg_hba.conf
    regexp: '^(host\s+all\s+all\s+127\.0\.0\.1/32\s+).*'
    line: 'host    all             all             127.0.0.1/32            md5'
    state: present

- name: Restart PostgreSQL service
  service:
    name: postgresql
    state: restarted

- name: Create PostgreSQL database
  community.postgresql.postgresql_db:
    name: stage_5b
    state: present
    login_user: postgres
    login_password: "{{ postgres_admin_password }}"

- name: Create PostgreSQL user
  community.postgresql.postgresql_user:
    name: hng_user
    password: "{{ postgres_user_password }}"
    db: stage_5b
    priv: "ALL"
    state: present

- name: Save PostgreSQL admin credentials
  copy:
    content: |
      DB_USER=postgres
      DB_PASSWORD={{ postgres_admin_password }}
    dest: /var/secrets/pg_pw.txt
    owner: hng
    group: hng
    mode: '0600'
